#!/usr/bin/env php
<?php
declare(strict_types = 1);

require __DIR__.'/vendor/autoload.php';

$version = '0.1.0-alpha';

$app = new Symfony\Component\Console\Application('git pr', $version);
$app->add(new \GitPullRequest\Application\InitCommand());
$app->add(new \GitPullRequest\Application\MergeCommand());
$app->run();
